export default ({
  ADD_QUIZZES: 'ADD_QUIZZES',
  REMOVE_QUIZZES: 'REMOVE_QUIZZES',
  EDIT_QUIZZES: 'EDIT_QUIZZES',

  ADD_QUIZ: "ADD_QUIZ",
  REMOVE_QUIZ: "REMOVE_QUIZ",
  EDIT_QUIZ: "EDIT_QUIZ",
});
