export const QUIZ_LIST_REQUEST = 'QUIZ_LIST_REQUEST';
export const QUIZ_LIST_SUCCESS = 'QUIZ_LIST_SUCCESS';
export const QUIZ_LIST_FAIL = 'QUIZ_LIST_FAIL';

export const QUIZ_ADD_REQUEST = 'QUIZ_ADD_REQUEST ';
export const QUIZ_ADD_SUCCESS = 'QUIZ_ADD_SUCCESS ';
export const QUIZ_ADD_FAIL = 'QUIZ_ADD_FAIL';

export const QUIZ_SAVE_REQUEST = 'QUIZ_SAVE_REQUEST ';
export const QUIZ_SAVE_SUCCESS = 'QUIZ_SAVE_SUCCESS ';
export const QUIZ_SAVE_FAIL = 'QUIZ_SAVE_FAIL ';

export const QUIZ_REMOVE_REQUEST = 'QUIZ_REMOVE_REQUEST ';
export const QUIZ_REMOVE_SUCCESS = 'QUIZ_REMOVE_SUCCESS ';
export const QUIZ_REMOVE_FAIL = 'QUIZ_REMOVE_FAIL';
