const ADD_QUESTION = 'ADD_QUESTION'
const REMOVE_QUESTION = 'REMOVE_QUESTION'
const ADD_OPTION_FOR_QUESTION = 'ADD_OPTION_FOR_QUESTION'
const REMOVE_OPTION_FOR_QUESTION = 'REMOVE_OPTION_FOR_QUESTION'
export default {
  ADD_OPTION_FOR_QUESTION, 
  ADD_QUESTION, 
  REMOVE_OPTION_FOR_QUESTION,
  REMOVE_QUESTION
}